// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5V7SueMt2DudueuG25NHToVBMnGuB6bY',
    appId: '1:61823089564:web:aa11e412b138c5634e2659',
    messagingSenderId: '61823089564',
    projectId: 'fluttercourse-174fe',
    authDomain: 'fluttercourse-174fe.firebaseapp.com',
    storageBucket: 'fluttercourse-174fe.appspot.com',
    measurementId: 'G-5PCVFW68FQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrirT-XObdQRaYtzfak5HFuF1KvvkODZY',
    appId: '1:61823089564:android:b2f68beabc1e95874e2659',
    messagingSenderId: '61823089564',
    projectId: 'fluttercourse-174fe',
    storageBucket: 'fluttercourse-174fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8T68N366RT1FiCKxr14-55rhxBEFv_mU',
    appId: '1:61823089564:ios:069fd26a47c75da84e2659',
    messagingSenderId: '61823089564',
    projectId: 'fluttercourse-174fe',
    storageBucket: 'fluttercourse-174fe.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8T68N366RT1FiCKxr14-55rhxBEFv_mU',
    appId: '1:61823089564:ios:069fd26a47c75da84e2659',
    messagingSenderId: '61823089564',
    projectId: 'fluttercourse-174fe',
    storageBucket: 'fluttercourse-174fe.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5V7SueMt2DudueuG25NHToVBMnGuB6bY',
    appId: '1:61823089564:web:a7984b5359166e214e2659',
    messagingSenderId: '61823089564',
    projectId: 'fluttercourse-174fe',
    authDomain: 'fluttercourse-174fe.firebaseapp.com',
    storageBucket: 'fluttercourse-174fe.appspot.com',
    measurementId: 'G-EMJWJL3XW4',
  );
}
